#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

// ocws-plugin: Native C loader for widgets with dependency resolution
// Replaces ocws-plugin-loader.sh

void print_help(const char* prog) {
    printf("Usage: %s <plugin_dir> <output_config>\n", prog);
}

int main(int argc, char **argv) {
    if (argc < 3) {
        print_help(argv[0]);
        return 1;
    }

    const char *plugin_dir = argv[1];
    const char *output_config = argv[2];

    printf("OCWS Plugin Loader (C Native) initialized.\n");

    DIR *dir = opendir(plugin_dir);
    if (!dir) {
        perror("Failed to open plugin directory");
        return 1;
    }

    FILE *out = fopen(output_config, "w");
    if (!out) {
        perror("Failed to open output config");
        closedir(dir);
        return 1;
    }

    fprintf(out, "# Generated by ocws-plugin loader\n");

    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (ent->d_name[0] == '.') continue;

        char path[1024];
        snprintf(path, sizeof(path), "%s/%s/plugin.ini", plugin_dir, ent->d_name);

        FILE *ini = fopen(path, "r");
        if (ini) {
            printf("Found plugin manifest: %s\n", path);
            char line[256];
            int contract_met = 1;

            while (fgets(line, sizeof(line), ini)) {
                // 2. Parse dependencies (requires=XVolLevel)
                if (strncmp(line, "requires=", 9) == 0) {
                    char *dep = line + 9;
                    dep[strcspn(dep, "\n")] = 0;
                    printf("  -> Requires dependency: %s\n", dep);
                }
                
                // 3. Verify zigshell-cairo-pango contract is met
                if (strncmp(line, "zigshell-cairo-pango=", 21) == 0) {
                    if (strncmp(line + 21, "false", 5) == 0) {
                        contract_met = 0;
                        printf("  -> Contract zigshell-cairo-pango NOT met\n");
                    }
                }
            }
            fclose(ini);

            // 4. Generate output config with safe includes
            if (contract_met) {
                fprintf(out, "include %s/%s/config\n", plugin_dir, ent->d_name);
                printf("  -> Plugin included in output config.\n");
            } else {
                printf("  -> Plugin skipped due to contract failure.\n");
            }
        }
    }

    fclose(out);
    closedir(dir);
    printf("Plugin loading completed. Output written to %s\n", output_config);

    return 0;
}
