#!/bin/bash
#
# theme.sh — Theme manager for labwc + GTK3/GTK4 + icons + cursors
#
# Applies complete desktop theme from profile INI files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
THEMES_DIR="$PROJECT_DIR/themes"
CONFIG_DIR="${HOME}/.config/labwc"
CURRENT_THEME_FILE="${HOME}/.config/labwc/current-theme"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

pass()  { echo -e "  ${GREEN}✓${NC} $1"; }
warn()  { echo -e "  ${YELLOW}⚠${NC} $1"; }
info()  { echo -e "  ${CYAN}→${NC} $1"; }
fail()  { echo -e "  ${RED}✗${NC} $1"; exit 1; }
section() { echo -e "\n${BOLD}[$1]${NC}"; }

# ============================================================
# INI Parser
# ============================================================

parse_ini() {
  local file="$1"
  local section=""
  while IFS='=' read -r key value; do
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    [[ -z "$key" || "$key" == \#* ]] && continue
    if [[ "$key" == \[*\] ]]; then
      section="${key//[\[\]]/}"
    elif [[ -n "$section" ]]; then
      echo "${section}.${key}=${value}"
    fi
  done < "$file"
}

get_value() {
  local data="$1"
  local key="$2"
  echo "$data" | grep "^${key}=" | head -1 | cut -d'=' -f2-
}

# ============================================================
# Apply labwc Theme
# ============================================================

apply_labwc_theme() {
  local data="$1"
  
  section "labwc Theme"
  
  local bg=$(get_value "$data" "labwc.themerc_bg")
  local active_bg=$(get_value "$data" "labwc.themerc_active_bg")
  local inactive_bg=$(get_value "$data" "labwc.themerc_inactive_bg")
  local active_text=$(get_value "$data" "labwc.themerc_active_text")
  local inactive_text=$(get_value "$data" "labwc.themerc_inactive_text")
  local border=$(get_value "$data" "labwc.themerc_border")
  local font=$(get_value "$data" "labwc.themerc_font")
  local height=$(get_value "$data" "labwc.themerc_height")
  
  # Generate themerc-override
  cat > "$CONFIG_DIR/themerc-override" << EOF
# labwc theme override
# Generated by theme.sh

activetextfont=${font:-sans 10}
activebg=${active_bg:-#313244}
activetext=${active_text:-#cdd6f4}

inactivetextfont=${font:-sans 10}
inactivebg=${inactive_bg:-#181825}
inactivetext=${inactive_text:-#6c7086}

border.width=1
border.color=${border:-#45475a}

titlebar.height=${height:-28}
EOF
  
  pass "themerc-override generated"
  
  # Reload labwc if running
  if pgrep -x labwc &>/dev/null; then
    labwc --reconfigure 2>/dev/null && pass "labwc reloaded" || warn "Could not reload labwc"
  fi
}

# ============================================================
# Apply GTK Theme
# ============================================================

apply_gtk_theme() {
  local data="$1"
  
  section "GTK Theme"
  
  local gtk3_theme=$(get_value "$data" "gtk3.gtk_theme")
  local gtk4_theme=$(get_value "$data" "gtk4.gtk_theme")
  local icon_theme=$(get_value "$data" "gtk3.icon_theme")
  local cursor=$(get_value "$data" "gtk3.cursor_theme")
  local color_scheme=$(get_value "$data" "gtk3.color_scheme")
  local prefer_dark=$(get_value "$data" "gtk3.gtk_application_prefer_dark_theme")
  local btn_layout=$(get_value "$data" "gtk3.button_layout")
  
  if command -v gsettings &>/dev/null; then
    # GTK3 settings
    gsettings set org.gnome.desktop.interface gtk-theme "${gtk_theme:-Adwaita-dark}" 2>/dev/null && \
      pass "GTK3 theme: $gtk_theme" || warn "Could not set GTK3 theme"
    
    gsettings set org.gnome.desktop.interface icon-theme "${icon_theme:-Adwaita}" 2>/dev/null && \
      pass "Icon theme: $icon_theme" || warn "Could not set icon theme"
    
    gsettings set org.gnome.desktop.interface cursor-theme "${cursor:-Adwaita}" 2>/dev/null && \
      pass "Cursor theme: $cursor" || warn "Could not set cursor theme"
    
    gsettings set org.gnome.desktop.interface cursor-size 24 2>/dev/null && \
      pass "Cursor size: 24" || warn "Could not set cursor size"
    
    # Color scheme
    if [ "$color_scheme" = "prefer-dark" ]; then
      gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null && \
        pass "Color scheme: dark" || warn "Could not set color scheme"
    else
      gsettings set org.gnome.desktop.interface color-scheme 'default' 2>/dev/null && \
        pass "Color scheme: light" || warn "Could not set color scheme"
    fi
    
    # Fonts
    local iface_font=$(get_value "$data" "fonts.interface")
    local mono_font=$(get_value "$data" "fonts.monospace")
    
    if [ -n "$iface_font" ]; then
      gsettings set org.gnome.desktop.interface font-name "$iface_font" 2>/dev/null && \
        pass "Interface font: $iface_font"
    fi
    
    if [ -n "$mono_font" ]; then
      gsettings set org.gnome.desktop.interface monospace-font-name "$mono_font" 2>/dev/null && \
        pass "Monospace font: $mono_font"
    fi
    
    # Button layout (for headerbar apps)
    if [ -n "$btn_layout" ]; then
      gsettings set org.gnome.desktop.wm.preferences button-layout "$btn_layout" 2>/dev/null && \
        pass "Button layout: $btn_layout"
    fi
  else
    warn "gsettings not found, skipping GTK configuration"
  fi
}

# ============================================================
# Apply Cursor Theme (via environment)
# ============================================================

apply_cursor_theme() {
  local data="$1"
  
  section "Cursor Theme"
  
  local cursor=$(get_value "$data" "gtk3.cursor_theme")
  local size="24"
  
  # Update environment file
  if [ -f "$CONFIG_DIR/environment" ]; then
    # Remove old cursor settings
    sed -i '/^XCURSOR_THEME=/d' "$CONFIG_DIR/environment"
    sed -i '/^XCURSOR_SIZE=/d' "$CONFIG_DIR/environment"
    
    # Add new cursor settings
    echo "XCURSOR_THEME=${cursor:-Adwaita}" >> "$CONFIG_DIR/environment"
    echo "XCURSOR_SIZE=$size" >> "$CONFIG_DIR/environment"
    
    pass "Cursor environment updated"
  fi
  
  # Also set via gsettings if available
  if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface cursor-theme "${cursor:-Adwaita}" 2>/dev/null
    gsettings set org.gnome.desktop.interface cursor-size "$size" 2>/dev/null
  fi
}

# ============================================================
# Apply Panel/Statusbar Theme
# ============================================================

apply_panel_theme() {
  local data="$1"
  
  section "Panel Theme"
  
  local bar_bg=$(get_value "$data" "panel.bar_bg")
  local bar_text=$(get_value "$data" "panel.bar_text")
  local bar_active=$(get_value "$data" "panel.bar_active")
  local bar_urgent=$(get_value "$data" "panel.bar_urgent")
  
  # Update statusbar CSS variables
  local css_file="${HOME}/.config/zebar/main/style.css"
  if [ -f "$css_file" ]; then
    # Backup
    cp "$css_file" "${css_file}.backup"
    
    # Update CSS variables
    sed -i "s|--bg-base: #[a-fA-F0-9]*;|--bg-base: ${bar_bg:-#1e1e2e};|" "$css_file"
    sed -i "s|--text-primary: #[a-fA-F0-9]*;|--text-primary: ${bar_text:-#cdd6f4};|" "$css_file"
    sed -i "s|--accent-blue: #[a-fA-F0-9]*;|--accent-blue: ${bar_active:-#89b4fa};|" "$css_file"
    sed -i "s|--accent-red: #[a-fA-F0-9]*;|--accent-red: ${bar_urgent:-#f38ba8};|" "$css_file"
    
    pass "Statusbar CSS updated"
  fi
}

# ============================================================
# Install Theme Dependencies
# ============================================================

install_theme_deps() {
  local data="$1"
  
  section "Checking Theme Dependencies"
  
  local gtk3_theme=$(get_value "$data" "gtk3.gtk_theme")
  local icon_theme=$(get_value "$data" "gtk3.icon_theme")
  local cursor=$(get_value "$data" "gtk3.cursor_theme")
  
  # Check if themes are installed
  local MISSING=()
  
  # Check GTK theme
  if [ -d "${HOME}/.themes/${gtk3_theme}" ] || [ -d "/usr/share/themes/${gtk3_theme}" ]; then
    pass "GTK theme installed: $gtk3_theme"
  else
    warn "GTK theme not found: $gtk3_theme"
    MISSING+=("$gtk3_theme")
  fi
  
  # Check icon theme
  if [ -d "${HOME}/.icons/${icon_theme}" ] || [ -d "/usr/share/icons/${icon_theme}" ]; then
    pass "Icon theme installed: $icon_theme"
  else
    warn "Icon theme not found: $icon_theme"
    MISSING+=("$icon_theme")
  fi
  
  # Check cursor theme
  if [ -d "${HOME}/.icons/${cursor}" ] || [ -d "/usr/share/icons/${cursor}" ]; then
    pass "Cursor theme installed: $cursor"
  else
    warn "Cursor theme not found: $cursor"
    MISSING+=("$cursor")
  fi
  
  if [ ${#MISSING[@]} -gt 0 ]; then
    echo ""
    info "Missing theme components:"
    for m in "${MISSING[@]}"; do
      echo "    - $m"
    done
    echo ""
    info "Install with:"
    info "  sudo apt install gtk-theme-${gtk3_theme,,} icon-theme-${icon_theme,,}"
    info "  Or download from:"
    info "    https://www.gnome-look.org/p/1277297 (Catppuccin)"
    info "    https://www.gnome-look.org/p/1462428 (Nordic)"
    info "    https://www.gnome-look.org/p/1390947 (Dracula)"
  fi
}

# ============================================================
# Apply Complete Theme
# ============================================================

apply_theme() {
  local theme_name="$1"
  local theme_file="$THEMES_DIR/${theme_name}.ini"
  
  if [ ! -f "$theme_file" ]; then
    fail "Theme not found: $theme_name"
  fi
  
  echo ""
  echo -e "${BOLD}== Applying Theme: $theme_name ==${NC}"
  
  # Parse theme
  local data
  data=$(parse_ini "$theme_file")
  
  # Install dependencies check
  install_theme_deps "$data"
  
  # Apply all components
  apply_labwc_theme "$data"
  apply_gtk_theme "$data"
  apply_cursor_theme "$data"
  apply_panel_theme "$data"
  
  # Save current theme
  echo "$theme_name" > "$CURRENT_THEME_FILE"
  
  # Summary
  echo ""
  section "Summary"
  pass "Theme '$theme_name' applied successfully"
  echo ""
  echo "Changes:"
  echo "  • labwc window decorations"
  echo "  • GTK3/GTK4 theme, icons, cursors, fonts"
  echo "  • Statusbar colors"
  echo "  • Environment variables"
  echo ""
  echo "Some changes require logout/login to take full effect."
  echo ""
}

# ============================================================
# List Available Themes
# ============================================================

list_themes() {
  echo ""
  echo -e "${BOLD}== Available Themes ==${NC}"
  echo ""
  
  local current=""
  if [ -f "$CURRENT_THEME_FILE" ]; then
    current=$(cat "$CURRENT_THEME_FILE")
  fi
  
  for theme_file in "$THEMES_DIR"/*.ini; do
    [ -f "$theme_file" ] || continue
    local name=$(basename "$theme_file" .ini)
    local desc=$(grep "^description=" "$theme_file" | head -1 | cut -d'=' -f2-)
    
    if [ "$name" = "$current" ]; then
      echo -e "  ${GREEN}●${NC} $name ${CYAN}(active)${NC}"
    else
      echo -e "  ○ $name"
    fi
    echo "    $desc"
  done
  echo ""
}

# ============================================================
# Show Current Theme
# ============================================================

show_current() {
  echo ""
  echo -e "${BOLD}== Current Theme ==${NC}"
  echo ""
  
  if [ -f "$CURRENT_THEME_FILE" ]; then
    local current=$(cat "$CURRENT_THEME_FILE")
    echo "  Theme: ${CYAN}$current${NC}"
    
    local theme_file="$THEMES_DIR/${current}.ini"
    if [ -f "$theme_file" ]; then
      local data
      data=$(parse_ini "$theme_file")
      
      echo ""
      echo "  GTK Theme:    $(get_value "$data" "gtk3.gtk_theme")"
      echo "  Icons:        $(get_value "$data" "gtk3.icon_theme")"
      echo "  Cursors:      $(get_value "$data" "gtk3.cursor_theme")"
      echo "  Color Scheme: $(get_value "$data" "gtk3.color_scheme")"
      echo "  Fonts:        $(get_value "$data" "fonts.interface")"
    fi
  else
    echo "  No theme applied yet"
  fi
  echo ""
}

# ============================================================
# Main
# ============================================================

ACTION="${1:-help}"
shift || true

case "$ACTION" in
  apply|set)
    THEME="${1:-}"
    if [ -z "$THEME" ]; then
      fail "Usage: $0 apply <theme-name>"
    fi
    apply_theme "$THEME"
    ;;
  list|ls)
    list_themes
    ;;
  current|show)
    show_current
    ;;
  preview)
    THEME="${1:-}"
    if [ -z "$THEME" ]; then
      fail "Usage: $0 preview <theme-name>"
    fi
    echo "Preview: $THEME"
    echo "Run '$0 apply $THEME' to apply"
    ;;
  help|--help|-h|*)
    echo ""
    echo -e "${BOLD}== Theme Manager ==${NC}"
    echo ""
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  apply <name>    Apply a theme"
    echo "  list            List available themes"
    echo "  current         Show current theme"
    echo "  preview <name>  Preview theme info"
    echo ""
    echo "Available themes:"
    for f in "$THEMES_DIR"/*.ini; do
      [ -f "$f" ] && echo "  - $(basename "$f" .ini)"
    done 2>/dev/null
    echo ""
    ;;
esac
