[General]
autoHide=false
launchers="show-desktop;chromium-browser;firefox;foot;separator;lxqt-lockscreen;lxqt-logout;separator"
position=1
screen=0
showApplicationMenu=true
showBatteryIndicator=true
showClock=true
showKeyboardLayout=true
showPager=false
showTaskManager=true
showTrash=true
showVersionChecker=true
showVolumeControl=true
showWifiManager=true
visibility=0
